### ISSUE TITLE
.NET Core conversion

### ISSUE THREAD

**Issue by riipah** [VocaDB/vocadb#544]
Model project should be converted to .NET Standard 2.0 first.

Then add new Web frontend project based on ASP.NET Core / .NET Core.

Then change Model to .NET Core.

What to do about the WCF interface? It is used by the Wiki integration and MikuBot. Could it be converted to gRPC or just use the REST APIs?

There shouldn't be too many .NET Framework / legacy ASP.NET dependencies.

- [X] Refactor JavaScript compilation to use Webpack (#5)
- [X] VocaDB.Model into .NET Standard (#597)
- [x] Add Web frontend based on ASP.NET Core (#598)
- [x] Find a replacement for WCF (#713)
- [x] VocaDB.Model into .NET Core (#765)
